name: Build and test
on: [ push ]

jobs:
  nix-ci:
    uses: christianharke/flake-commons/.github/workflows/nix-ci.yml@main
    with:
      branch: ${{ github.ref_name }}
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  nix-ci-arm:
    uses: christianharke/flake-commons/.github/workflows/nix-ci-arm.yml@nix-on-droid-ci
    with:
      branch: ${{ github.ref_name }}
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
