name: Build and test
on: [ push ]

jobs:
  nix-ci-x86:
    uses: christianharke/flake-commons/.github/workflows/nix-ci.yml@main
    with:
      branch: 'main'
      system: 'x86_64'
  nix-ci-arm:
    uses: christianharke/flake-commons/.github/workflows/nix-ci.yml@main
    with:
      branch: 'main'
      system: 'aarch64'
