name: Nix - Build and test
on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: main
        type: string
      nix-command:
        description: 'Extra Nix command to run'
        required: false
        default: flake check
        type: string
      system:
        description: 'System architecture to run on'
        required: false
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false
        description: 'Token to authenticate against Cachix'
      DEPLOY_KEY_SUBMODULES:
        required: false
        description: 'Deploy key for checking out submodules'
      KNOWN_HOSTS:
        required: false
        description: 'Content of the known_hosts file'

jobs:
  nix:
    if: inputs.system == null || inputs.system == 'x86_64-linux' || inputs.system == 'x86_64-darwin'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Free disk space
        if: (inputs.system == null || endsWith(inputs.system, 'linux')) && startsWith(matrix.os, 'ubuntu')
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - name: Configure SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY_SUBMODULES }}

      - name: Add known_hosts file
        run: |
          mkdir -p ~/.ssh && echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts

      - name: Checkout repository
        if: inputs.system == null || (startsWith(matrix.os, 'macos') && endsWith(inputs.system, 'darwin') || startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux'))
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
          submodules: recursive

      - name: Install Nix
        if: inputs.system == null || (startsWith(matrix.os, 'macos') && endsWith(inputs.system, 'darwin') || startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux'))
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Use GitHub Nix Cache
        if: inputs.system == null || (startsWith(matrix.os, 'macos') && endsWith(inputs.system, 'darwin') || startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux'))
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Use Cachix Nix Cache
        if: inputs.system == null || (startsWith(matrix.os, 'macos') && endsWith(inputs.system, 'darwin') || startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux'))
        uses: cachix/cachix-action@v15
        with:
          name: christianharke
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and Test
        if: inputs.system == null || (startsWith(matrix.os, 'macos') && endsWith(inputs.system, 'darwin') || startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux'))
        run: |
          nix \
            --print-build-logs \
            --keep-going \
            ${{ inputs.nix-command }}
