name: Nix - Build and test
on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: main
        type: string
      nix-command:
        description: 'Extra Nix command to run'
        required: false
        default: flake check
        type: string
      system:
        description: 'System architecture to run on'
        default: x86_64-linux
        required: false
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false
        description: 'Token to authenticate against Cachix'

jobs:
  nix:
    if: inputs.system != 'aarch64-linux'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        if: startsWith(matrix.os, 'macos') && endsWith(inputs.system, 'darwin') || startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux')
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0

      - name: Free Disk Space
        if: startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux')
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false

      - name: Install nix
        if: startsWith(matrix.os, 'macos') && endsWith(inputs.system, 'darwin') || startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux')
        uses: cachix/install-nix-action@v18

      - name: Use nix cache
        if: startsWith(matrix.os, 'macos') && endsWith(inputs.system, 'darwin') || startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux')
        uses: cachix/cachix-action@v12
        with:
          name: christianharke
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build command
        if: startsWith(matrix.os, 'macos') && endsWith(inputs.system, 'darwin') || startsWith(matrix.os, 'ubuntu') && endsWith(inputs.system, 'linux')
        run: |
          nix \
            --print-build-logs \
            --keep-going \
            ${{ inputs.nix-command }}

