name: Nix - Update inputs
on:
  workflow_call:
    inputs:
      base-branch:
        description: 'Base branch to update'
        required: false
        type: string
        default: 'main'
      x86_64:
        description: 'Test update on x86'
        required: false
        type: boolean
        default: true
      aarch64:
        description: 'Test update on ARM'
        required: false
        type: boolean
        default: false

jobs:
  update:
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.branch.outputs.name }}
      update_available: ${{ steps.commit.outputs.changes_detected }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_PAT || github.token }}
          fetch-depth: 0

      - name: Install nix
        uses: cachix/install-nix-action@v18

      - name: Update inputs
        run: nix flake update

      - name: Set branch name output
        id: branch
        run: echo "name=ci/automatic-update-$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Create branch locally
        run: git switch -c ${{ steps.branch.outputs.name }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        id: commit
        with:
          commit_author: Christian Harke <christian@harke.ch>
          commit_message: "flake.inputs: automatic update"
          branch: ${{ steps.branch.outputs.name }}
          push_options: --force

  build_x86_64:
    uses: christianharke/flake-commons/.github/workflows/nix-ci.yml@main
    needs: update
    if: needs.update.outputs.update_available == 'true' && inputs.x86_64
    with:
      branch: ${{ needs.update.outputs.branch }}
      system: x86_64

  build_aarch64:
    uses: christianharke/flake-commons/.github/workflows/nix-ci.yml@main
    needs: update
    if: needs.update.outputs.update_available == 'true' && inputs.aarch64
    with:
      branch: ${{ needs.update.outputs.branch }}
      system: aarch64

  merge:
    runs-on: ubuntu-latest
    needs:
      - update
      - build_x86_64
      - build_aarch64
    if: always() && needs.update.outputs.update_available == 'true' && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if update branch is behind ${{ inputs.base-branch }}
        run: git diff origin/${{ needs.update.outputs.branch }}...origin/${{ inputs.base-branch }} --exit-code

      - name: Merge update into ${{ inputs.base-branch }}
        run: git merge origin/${{ needs.update.outputs.branch }}

      - name: Push ${{ inputs.base-branch }}
        run: git push origin ${{ inputs.base-branch }}

      - name: Delete update branch
        run: git push --delete origin ${{ needs.update.outputs.branch }}
