name: Update inputs
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.branch.outputs.name }}
      update_available: ${{ steps.commit.outputs.changes_detected }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install nix
        uses: cachix/install-nix-action@v18

      - name: Update inputs
        run: nix flake update

      - name: Set branch name output
        id: branch
        run: echo "name=ci/automatic-update-$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Create branch locally
        run: git switch -c ${{ steps.branch.outputs.name }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        id: commit
        with:
          commit_author: Christian Harke <christian@harke.ch>
          commit_message: "flake.inputs: automatic update"
          branch: ${{ steps.branch.outputs.name }}
          push_options: --force

  build:
    uses: christianharke/flake-commons/.github/workflows/ci.yml@main
    needs: update
    if: needs.update.outputs.update_available == 'true'
    with:
      branch: ${{ needs.update.outputs.branch }}

  merge:
    runs-on: ubuntu-latest
    needs:
      - update
      - build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if update branch is behind main
        run: git diff origin/${{ needs.update.outputs.branch }}...origin/main --exit-code

      - name: Merge update into main
        run: git merge origin/${{ needs.update.outputs.branch }}

      - name: Push main
        run: git push origin main

      - name: Delete update branch
        run: git push --delete origin ${{ needs.update.outputs.branch }}
