---
name: "Update inputs"
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * *"

jobs:
  nix-update:
    uses: "rake5k/flake-commons/.github/workflows/nix-update.yml@main"
    with:
      aarch64: false
      x86_64: true
    secrets:
      CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
