---
name: "Update inputs"
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nix-update:
    uses: "rake5k/flake-commons/.github/workflows/nix-update.yml@garnix-update"
    secrets:
      CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
